export interface Loc { id: string; name: string; x: number; y: number; w: number; h: number; spot: [number, number]; category: string; blurb: string; }
export const LOCATIONS: Loc[] = [
  { id: "square", name: "The Square", x: 96, y: 55, w: 18, h: 15, spot: [104, 62], category: "Social", blurb: "Tempat berkumpul utama." },
  { id: "hall", name: "The Town Hall", x: 98, y: 42, w: 9, h: 6, spot: [104, 50], category: "Civic", blurb: "Tempat voting." },
  { id: "market", name: "The Market", x: 84, y: 62, w: 8, h: 5, spot: [90, 66], category: "Work", blurb: "Pasar wol." },
  { id: "tavern", name: "The Wet Fleece", x: 116, y: 60, w: 7, h: 5, spot: [120, 66], category: "Social", blurb: "Kedai." },
  { id: "press", name: "The Daily Spit", x: 118, y: 44, w: 7, h: 5, spot: [122, 50], category: "Work", blurb: "Percetakan." },
  { id: "bank", name: "The Bank", x: 80, y: 44, w: 7, h: 5, spot: [86, 50], category: "Work", blurb: "Buku besar." },
  { id: "vault", name: "The Vault", x: 67, y: 45, w: 6, h: 4, spot: [72, 50], category: "Civic", blurb: "Gudang." },
  { id: "library", name: "The Library", x: 131, y: 46, w: 7, h: 5, spot: [136, 52], category: "Work", blurb: "Perpustakaan." },
  { id: "booth", name: "The Fork Booth", x: 99, y: 71, w: 7, h: 4, spot: [104, 76], category: "Civic", blurb: "Bilik fork." },
  { id: "clinic", name: "The Clinic", x: 130, y: 63, w: 7, h: 4, spot: [134, 68], category: "Work", blurb: "Klinik." },
  { id: "school", name: "The School", x: 68, y: 63, w: 7, h: 4, spot: [74, 68], category: "Work", blurb: "Sekolah." },
  { id: "post", name: "The Post Office", x: 143, y: 57, w: 7, h: 4, spot: [148, 62], category: "Work", blurb: "Kantor pos." },
  { id: "baths", name: "The Baths", x: 54, y: 57, w: 7, h: 4, spot: [60, 62], category: "Social", blurb: "Pemandian." },
  { id: "station", name: "The Station", x: 162, y: 52, w: 11, h: 5, spot: [170, 58], category: "Civic", blurb: "Stasiun." },
  { id: "barn", name: "The Barn", x: 36, y: 36, w: 11, h: 7, spot: [44, 44], category: "Rest", blurb: "Kandang tidur." },
  { id: "shed", name: "The Shearing Shed", x: 44, y: 80, w: 9, h: 6, spot: [52, 86], category: "Work", blurb: "Shed." },
  { id: "mill", name: "The Mill", x: 170, y: 78, w: 8, h: 7, spot: [176, 86], category: "Work", blurb: "Kincir." },
  { id: "pens", name: "The Pens", x: 76, y: 84, w: 18, h: 12, spot: [84, 90], category: "Rest", blurb: "Pens." },
  { id: "pond", name: "The Pond", x: 136, y: 86, w: 20, h: 13, spot: [146, 92], category: "Water", blurb: "Kolam." },
  { id: "dock", name: "The Dock", x: 144, y: 96, w: 8, h: 5, spot: [148, 100], category: "Social", blurb: "Dermaga." },
  { id: "meadowW", name: "The West Meadow", x: 16, y: 60, w: 24, h: 20, spot: [30, 70], category: "Food", blurb: "Rumput bagus." },
  { id: "meadowE", name: "The East Meadow", x: 172, y: 30, w: 24, h: 18, spot: [186, 40], category: "Food", blurb: "Rumput masam." },
  { id: "orchard", name: "The Orchard", x: 28, y: 96, w: 22, h: 16, spot: [40, 104], category: "Food", blurb: "Kebun apel." },
  { id: "trough", name: "The Trough", x: 94, y: 83, w: 6, h: 3, spot: [96, 84], category: "Food", blurb: "Palung." },
  { id: "fire", name: "The Fire", x: 108, y: 82, w: 5, h: 4, spot: [110, 84], category: "Social", blurb: "Api unggun." },
  { id: "board", name: "The Notice Board", x: 103, y: 57, w: 3, h: 2, spot: [104, 58], category: "Civic", blurb: "Papan pengumuman." },
];
